from __future__ import annotations

from copy import deepcopy
from typing import Any


_THEMES: dict[str, dict[str, Any]] = {
    "minimal": {
        "bg": "#f8fafc",
        "panel": "#ffffff",
        "panel_alt": "#f1f5f9",
        "plot_bg": "#f8fafc",
        "text_primary": "#0f172a",
        "text_secondary": "#334155",
        "text_muted": "#64748b",
        "grid": "#cbd5e1",
        "grid_strong": "#94a3b8",
        "accent": "#2563eb",
        "accent_alt": "#0f766e",
        "positive": "#059669",
        "negative": "#dc2626",
        "neutral": "#475569",
        "track": "#e2e8f0",
        "annotation_fill": "#dbeafe",
        "annotation_stroke": "#1d4ed8",
        "header_fill": "#e2e8f0",
        "series": ["#2563eb", "#0f766e", "#dc2626", "#d97706", "#7c3aed", "#0891b2"],
        "card_fills": ["#eff6ff", "#ecfeff", "#fef3c7", "#f5f3ff"],
        "font_title": "'Space Grotesk', 'Pretendard', 'Apple SD Gothic Neo', sans-serif",
        "font_body": "'Space Grotesk', 'Pretendard', 'Apple SD Gothic Neo', sans-serif",
        "font_mono": "'SFMono-Regular', 'JetBrains Mono', monospace",
        "title_size": 28,
        "subtitle_size": 18,
        "body_size": 16,
        "tick_size": 14,
        "source_size": 14,
        "stat_size": 72,
        "radius_card": 22,
        "radius_chip": 12,
    },
    "editorial": {
        "bg": "#fbf7ef",
        "panel": "#fffdfa",
        "panel_alt": "#f3ece1",
        "plot_bg": "#fffaf2",
        "text_primary": "#1f1a17",
        "text_secondary": "#5e5147",
        "text_muted": "#8a7768",
        "grid": "#d8cfc4",
        "grid_strong": "#baa78f",
        "accent": "#b45309",
        "accent_alt": "#7c2d12",
        "positive": "#0f766e",
        "negative": "#b91c1c",
        "neutral": "#57534e",
        "track": "#efe7db",
        "annotation_fill": "#ffedd5",
        "annotation_stroke": "#c2410c",
        "header_fill": "#efe4d3",
        "series": ["#b45309", "#7c2d12", "#c2410c", "#0f766e", "#7c3aed", "#0f766e"],
        "card_fills": ["#fff1df", "#f7ebda", "#fff6e7", "#f8efe7"],
        "font_title": "'Space Grotesk', 'Pretendard', 'Apple SD Gothic Neo', sans-serif",
        "font_body": "'IBM Plex Sans KR', 'Pretendard', 'Apple SD Gothic Neo', sans-serif",
        "font_mono": "'SFMono-Regular', 'JetBrains Mono', monospace",
        "title_size": 30,
        "subtitle_size": 18,
        "body_size": 16,
        "tick_size": 14,
        "source_size": 14,
        "stat_size": 72,
        "radius_card": 22,
        "radius_chip": 12,
    },
    "dashboard": {
        "bg": "#f3f8fa",
        "panel": "#ffffff",
        "panel_alt": "#e6f4f3",
        "plot_bg": "#f8fcfc",
        "text_primary": "#0f172a",
        "text_secondary": "#164e63",
        "text_muted": "#4b5563",
        "grid": "#cbd5e1",
        "grid_strong": "#94a3b8",
        "accent": "#0f766e",
        "accent_alt": "#0891b2",
        "positive": "#16a34a",
        "negative": "#dc2626",
        "neutral": "#475569",
        "track": "#dbe7ec",
        "annotation_fill": "#ccfbf1",
        "annotation_stroke": "#0f766e",
        "header_fill": "#dff5f1",
        "series": ["#0f766e", "#0891b2", "#2563eb", "#d97706", "#7c3aed", "#0ea5e9"],
        "card_fills": ["#e6fffb", "#eefcfb", "#eff6ff", "#f0fdfa"],
        "font_title": "'Space Grotesk', 'Pretendard', 'Apple SD Gothic Neo', sans-serif",
        "font_body": "'IBM Plex Sans KR', 'Pretendard', 'Apple SD Gothic Neo', sans-serif",
        "font_mono": "'SFMono-Regular', 'JetBrains Mono', monospace",
        "title_size": 28,
        "subtitle_size": 18,
        "body_size": 16,
        "tick_size": 14,
        "source_size": 14,
        "stat_size": 72,
        "radius_card": 22,
        "radius_chip": 12,
    },
    "clay": {
        "bg": "#bce5cf",
        "panel": "#d1ecde",
        "panel_alt": "#b5dec5",
        "plot_bg": "#c7e8d5",
        "text_primary": "#2a2420",
        "text_secondary": "#5a4e48",
        "text_muted": "#8a7d75",
        "grid": "#a4d4b8",
        "grid_strong": "#7fb998",
        "accent": "#8b5a9f",
        "accent_alt": "#d47a8e",
        "positive": "#6fa877",
        "negative": "#d16a6a",
        "neutral": "#a89a92",
        "track": "#a4d4b8",
        "annotation_fill": "#f4d9c8",
        "annotation_stroke": "#b85a7a",
        "header_fill": "#b5dec5",
        "series": ["#8b5a9f", "#e69b80", "#7bb7a5", "#d87a7a", "#f2c57c", "#a4c8e8"],
        "card_fills": ["#d1ecde", "#e4d4dc", "#f2e4d4", "#d8e0ec"],
        "font_title": "'Space Grotesk', 'Pretendard', 'Apple SD Gothic Neo', sans-serif",
        "font_body": "'Space Grotesk', 'Pretendard', 'Apple SD Gothic Neo', sans-serif",
        "font_mono": "'SFMono-Regular', 'JetBrains Mono', monospace",
        "title_size": 30,
        "subtitle_size": 18,
        "body_size": 16,
        "tick_size": 14,
        "source_size": 14,
        "stat_size": 72,
        "radius_card": 28,
        "radius_chip": 16,
    },
    "broadcast": {
        "bg": "#09111f",
        "panel": "#0f1b32",
        "panel_alt": "#13213d",
        "plot_bg": "#0b1730",
        "text_primary": "#f8fafc",
        "text_secondary": "#dbeafe",
        "text_muted": "#93c5fd",
        "grid": "#334155",
        "grid_strong": "#475569",
        "accent": "#f97316",
        "accent_alt": "#22d3ee",
        "positive": "#4ade80",
        "negative": "#fb7185",
        "neutral": "#94a3b8",
        "track": "#1e293b",
        "annotation_fill": "#7c2d12",
        "annotation_stroke": "#fb923c",
        "header_fill": "#1e293b",
        "series": ["#f97316", "#22d3ee", "#4ade80", "#facc15", "#a78bfa", "#fb7185"],
        "card_fills": ["#13213d", "#162742", "#11203b", "#182a49"],
        "font_title": "'Space Grotesk', 'Pretendard', 'Apple SD Gothic Neo', sans-serif",
        "font_body": "'IBM Plex Sans KR', 'Pretendard', 'Apple SD Gothic Neo', sans-serif",
        "font_mono": "'SFMono-Regular', 'JetBrains Mono', monospace",
        "title_size": 28,
        "subtitle_size": 18,
        "body_size": 16,
        "tick_size": 14,
        "source_size": 14,
        "stat_size": 72,
        "radius_card": 22,
        "radius_chip": 12,
    },
}


def get_theme_tokens(theme_name: str) -> dict[str, Any]:
    theme = _THEMES.get(theme_name) or _THEMES["minimal"]
    return deepcopy(theme)
